---

- hosts: all
  become: true
  tasks:
  
  #- name: update repo index
  #  apt:
  #    update_cache: yes
  #  #when: ansible_distribution == "Debian"
  #  when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install neofetch package
    package:
      name:
        - neofetch
      state: latest
      update_cache: yes
